/*
 * Settings.
 *
 * Two NVS partitions, so reflashing the settings never loses the pairing:
 *  - "cfg" (namespace "korvo"): what the user sets, written by flash.py
 *    (--config-only rewrites only this partition) or by the Wi-Fi setup page:
 *    wifi_ssid, wifi_pass, server_url, name, room, owner, led_bright (0-100),
 *    led_idle (0 off / 1 dim breathing), mic_gain (dB), dac_volume (0-100).
 *  - "nvs" (namespace "korvo_id" + "korvo_rt"): generated by the device and
 *    kept forever: device_id ("korvo-<MAC>"), token (32 random bytes,
 *    base64url); runtime state: volume, mic_muted, ref_lane, mic_lane.
 */
#pragma once

#include <stdint.h>

#include "esp_err.h"

#define DEFAULT_SERVER_URL "ws://assistant.local:8765/v1/device"

typedef struct {
    char wifi_ssid[33];
    char wifi_pass[65];
    char server_url[160];
    char name[64];
    char room[64];
    char owner[48];
    uint8_t led_bright;
    uint8_t led_idle;
    uint8_t mic_gain;
    uint8_t dac_volume;
    /* identity */
    char device_id[48];
    char token[64];
    /* runtime */
    uint8_t volume;
    uint8_t mic_muted;
    int8_t ref_lane, mic_lane;
    uint32_t boot_count;
} config_t;

extern config_t g_cfg;

esp_err_t config_init(void);
/* Wi-Fi setup page / server config message: saves to the "cfg" partition. */
esp_err_t config_save_user(void);
esp_err_t config_save_runtime(void);
